# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-11 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instarock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profilepic',
            field=models.CharField(default='', max_length=225),
        ),
    ]
